### ISSUE TITLE
rvm.io facelift

### ISSUE THREAD

**Issue by lixonic** [rvm/rvm-site#233]
finally got some spare time and did this > http://kuppis.github.io/rvmio

Not sure about the colors though.

**Comment by mpapis** [comment]
what's the status here?

**Comment by lixonic** [comment]
![mokey](https://cloud.githubusercontent.com/assets/934220/5645262/3b954b06-9693-11e4-9c05-4a7b68b890a6.jpg)

**Comment by johnivanoff** [comment]
Crud. This made me realize I forgot to make a pull request. I pushed a few
weeks ago. Sorry.

**Comment by lixonic** [comment]
removed the body background, gave one to the header. desperate?
![rvm](https://cloud.githubusercontent.com/assets/934220/5657182/28e2c9fc-9710-11e4-9967-7162e863ff4e.png)

**Comment by mpapis** [comment]
ah all the advertisement goes away, it's been full year as promised in the description, I will open separate PR to remove it .. as for new design, **I do not know** - it's not my domain :( I would need to see it and play with it, maybe open a PR like https://github.com/rvm/rvm-site/pull/240 and then I can run it locally

**Comment by lixonic** [comment]
ok great! 
@johnivanoff lets fight :)

**Comment by mpapis** [comment]
or you could try to work together on something

**Comment by johnivanoff** [comment]
:-)

When do the sponsors go away? Maybe we work on that look and then "cram" in
the sponsors knowing that they will go away?

Regarding "mobile" I know 99% is desktop. But I also use my phone to look
up RVM stuff while talking to people. This "older" person has a difficult
time reading 10pt font now. :-) I'm trying to get "looks good. I can use it
where ever" feel. I use it for information. Not trying to get design
awards. :-) I'm flexible. Not sold an any design. I thought about moving
the sponsors to the bottom of the page for small screens but I don't know
if they _have_ to stay at the top.

John

**Comment by mpapis** [comment]
already gone, needed to push deploy

**Comment by johnivanoff** [comment]
That changes things. I guess that also proves I haven't looked at
production in a while I feel shame.

**Comment by lixonic** [comment]
pushed a minimal version. used new logo

**Comment by mpapis** [comment]
@lixonic having issues finding time for anything, will check as soon as I can, @johnivanoff how o you like the update?

**Comment by lixonic** [comment]
![rvm](https://cloud.githubusercontent.com/assets/934220/5956309/aace7eb6-a7d2-11e4-8af3-a2768ed84f9c.png)

**Comment by lixonic** [comment]
another one . gives more space to docindex
![rvm 2](https://cloud.githubusercontent.com/assets/934220/5956572/3d0f64a0-a7d5-11e4-8c19-0a047db66aba.png)
