### ISSUE TITLE
reference to file which does not exist

### ISSUE THREAD

**Issue by ian-kelling** [rvm/rvm-site#258]
https://rvm.io/rvm/best-practices
'e.g. check out the rvmrc in the rvm-site(link to this repo) '
however, this repo does not contain an rvmrc file.

Also, the readme file for this repo says
"If you are in RVM and have 2.0.0 already running, simply clone this repository and cd to
the directory. The project `.rvmrc` will be loaded and you can open in your editor and
start hacking away."

**Comment by digitalfrost** [comment]
Thanks for pointing this out

The example .rvmrc file can be found here:
https://github.com/rvm/rvm/tree/master/examples

I will update the docs.
