### ISSUE TITLE
Missing information that user should have sudo rights

### ISSUE THREAD

**Issue by sampablokuper** [rvm/rvm-site#262]
That page's instructions include the following:

> First ensure that the previous step was successful and that rvm is loaded correctly. To do this, and verify that RVM is loaded as a shell function, run: `type rvm | head -1`
> 
> Assuming this shows "rvm is a function", you're good to go. As an example, to install and use Ruby 2.1.1 you may do:
> 
>    `$ rvm install 2.1.1`

However, it is false to assume the user is "good to go" at that point. That is because currently `rvm install` expects the user to have sudo rights, whereas the user may not in fact have sudo rights - in which case the user is _not_ good to go, and the install attempt [may fail](https://github.com/rvm/rvm/issues/3411).

**Comment by ExClouds** [comment]
running install command as sudo fixed the problem for me. Tnx.

**Comment by mpapis** [comment]
indeed this should be mentioned somewhere, especially in the installation instructions or some notes, something like:

> RVM calls `sudo` internally if/when it is needed.
