### ISSUE TITLE
Dead link to blip.tv breaks Travis build

### ISSUE THREAD

**Issue by digitalfrost** [rvm/rvm-site#265]
Travis build fails with this error
```
[ ERROR ] external_links - broken reference to http://blip.tv/akitaonrails/railsconf-2010-wayne-e-seguin-3785213: execution expired
  public/packages/zlib/index.html:
```
Blip.tv shut down in August: http://variety.com/2015/digital/news/maker-studios-is-shutting-down-blip-next-month-1201544219/

**Comment by digitalfrost** [comment]
How about changing the link to 
[MountainWest RubyConf 2010 - Managing Ruby Projects with RVM by Wayne E. Seguin](https://www.youtube.com/watch?v=O7M0tTJc9mY) on Youtube ?

**Comment by mpapis** [comment]
this should work, could you open a PR for that?

**Comment by digitalfrost** [comment]
Sure will do

**Comment by digitalfrost** [comment]
Actually looking at the code it's the same video as the link above on Confreaks MWRC 2010. I've found some links to RailsConf presentations. See pull request.

**Comment by mpapis** [comment]
great, thank you, will merge as soon the build passes

**Comment by joshschoolie91** [comment]
I have a link to a bliptv video I really need to retrieve or get the audio atleast from it.. Is there any way I can take the link and get something to work? Please help. I really need this to happen.
