### ISSUE TITLE
rvm.io is down

### ISSUE THREAD

**Issue by Jasonbit** [rvm/rvm-site#281]
The site worked for me this morning and it looks like the domain is parked now. Maybe the domain name ran out or was hijacked?

**Comment by jrgifford** [comment]
Interesting - according to the whois record, we renewed it so it'll expire in 2017. Maybe there is a glitch with the DNS server.

**Comment by sethrosenblum** [comment]
When I go to the site I get a gray screen and errors about mixed-content:
![Chrome errors](https://www.dropbox.com/s/3isvu63tko98ov6/Screenshot%202015-12-30%2015.08.10.png?dl=1)

**Comment by mpapis** [comment]
we did not get any warning the domain is expiring from dnsimple, since then we got it paid and dns should be already propagated with proper addresses.
