### ISSUE TITLE
Error while trying to install ruby 2.1.5

### ISSUE THREAD

**Issue by jdubb45** [rvm/rvm-site#290]
I receive the following while trying to install 2.1.5

ruby-2.1.5 - #removing src/ruby-2.1.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.1.5, this may take a while depending on your cpu(s)...
ruby-2.1.5 - #downloading ruby-2.1.5, this may take a while depending on your connection...
ruby-2.1.5 - #extracting ruby-2.1.5 to /usr/local/rvm/src/ruby-2.1.5....
ruby-2.1.5 - #configuring.....................................................
ruby-2.1.5 - #post-configuration..
ruby-2.1.5 - #compiling...............................................................................
Error running '__rvm_make -j2',
showing last 15 lines of /usr/local/rvm/log/1471531329_ruby-2.1.5/make.log
make[2]: *** [ossl_ssl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/usr/local/rvm/src/ruby-2.1.5/ext/pty'
compiling pty.c
installing default pty libraries
linking shared-object pty.so
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5/ext/openssl'
exts.mk:192: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5/ext/pty'
make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5'
uncommon.mk:180: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

   OSSL_SSL_METHOD_ENTRY(SSLv3),
                          ^
ossl_ssl.c:115:69: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
ossl_ssl.c:138:27: error: ‘SSLv3_server_method’ undeclared here (not in a function)
    OSSL_SSL_METHOD_ENTRY(SSLv3_server),
                          ^
ossl_ssl.c:115:69: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
ossl_ssl.c:139:27: error: ‘SSLv3_client_method’ undeclared here (not in a function)
    OSSL_SSL_METHOD_ENTRY(SSLv3_client),
                          ^
ossl_ssl.c:115:69: note: in definition of macro ‘OSSL_SSL_METHOD_ENTRY’
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
Makefile:280: recipe for target 'ossl_ssl.o' failed
make[2]: *** [ossl_ssl.o] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20160818010906.49608/ruby-2.1.5/ext/openssl'
exts.mk:191: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
checking ../.././parse.y and ../.././ext/ripper/eventids2.c
installing default ripper libraries
linking shared-object ripper.so

**Comment by lpaulmp** [comment]
@jdubb45  did you try to use an old version?

**Comment by jdubb45** [comment]
RVM has been giving me a headache. Instead of using Kali i installed it on Ubuntu. I'm now having issues with passenger. :(

**Comment by jdubb45** [comment]
In ubuntu 14.04 i get the following when i run both of these commands

rvm all do gem install --no-rdoc --no-ri rails
rvm all do gem install --no-rdoc --no-ri passenger

Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: minitest-5.9.0.gem (100%)
Successfully installed minitest-5.9.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2.
jdubb@ubuntu:~$

**Comment by pkuczynski** [comment]
Please report your issues regarding RVM in here: https://github.com/rvm/rvm/issues

This repo is only about RVM site.
