### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by mmoll** [rvm/rvm-site#320]
`The certificate expired on August 23, 2017, 1:10 PM. The current time is August 23, 2017, 1:51 PM.`

**Comment by mmoll** [comment]
This also makes some downloads failing e.g. from https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64

**Comment by CristianCantoro** [comment]
@mmoll beat me to it.

Also `rvm get stable` fails
```bash
Downloading https://get.rvm.io
Could not download rvm-installer, get some help at #rvm IRC channel at freenode servers.
```

**Comment by jahio** [comment]
Cause: 90-day default expiration date, non-negotiable, explained [here](https://letsencrypt.org/2015/11/09/why-90-days.html)

Solution: for now manually renew and install the new cert; going forward, [teh googlez show that many have faced and automated renewals for letsencrypt](https://www.google.com/search?q=letsencrypt+automation&client=opera&hs=lIY&source=lnt&tbs=qdr:y&sa=X&ved=0ahUKEwj57M7Fuu3VAhVE8IMKHfatCWQQpwUIHg&biw=1029&bih=871)

**Comment by jahio** [comment]
Same thing reported in better form at rvm/rvm -- https://github.com/rvm/rvm/issues/4129

Just saw in the slack channel that this has been addressed by @mpapis:

> [8:13]
> fixed
> 
> [8:14] 
> I thought it was fixed, but those hooks are hard to investigate

I believe the failure was in automation to restart `nginx` but would welcome clarifying comments from those more familiar with the precise details than I 😃 

And just to wrap this up nicely, I _was_ seeing the cert expiration problem earlier this morning and re-checked just now: indeed this seems solved.

**Comment by mmoll** [comment]
sad to hear "slack"... but it's fixed now.

**Comment by mpapis** [comment]
indeed it was lack of nginx restart, I have written a new script to ensure this is solved https://github.com/rvm/rvm-site-setup/commit/6dd0db5ebaee3f9a686e2e895a0dd3b161345d6c

**Comment by Startouf** [comment]
Hello, it would seem the certificate expired again on October 21st 2017

**Comment by AlexandreHauber** [comment]
Is this happening again? October 2021?
