### ISSUE TITLE
Donation Buttons are Broken

### ISSUE THREAD

**Issue by zeroalpha** [rvm/rvm-site#327]
Hi,

i was trying to donate a few bucks to the Project, but bountysource keeps coming back with:

> The content that you are looking for does not exist.
> Bountysource has changed!

**Comment by havenwood** [comment]
I can confirm that this is still an issue. Thanks for the report!

**Comment by havenwood** [comment]
Also, BountySource generally doesn't seem to function anymore. I'm getting a 500 for the RVM page and it seems broken overall.

**Comment by havenwood** [comment]
Closed by acbaaa1a96d32d5e37ec22b3395ec17b1ce8fe2d.
