### ISSUE TITLE
Publishing the latest version of site

### ISSUE THREAD

**Issue by eddietejeda** [rvm/rvm-site#348]
The [live site ](https://rvm.io/rvm/install) makes reference to `pool.sks-keyservers.net `, a service that no longer exists.

On Jul 31, 2021, [this pull request](https://github.com/rvm/rvm-site/pull/345) was merged to master and should resolve the issue.

But the live site still makes reference to the old URL. What do we need to publish the latest version of the content to the site?

**Comment by jaygooby** [comment]
Just bumped into the same problem after going to install a new dev machine
